#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 Yamato Okada
# SPDX-License-Identifier: BSD-3-Clause

import sys
import re
import signal

signal.signal(signal.SIGPIPE, signal.SIG_DFL)

def main():
    for line in sys.stdin:
        original_line = line
        line = line.strip()
        if not line:
            continue

        ascii_count = len(re.findall(r'[ -~]', line))
        total_count = len(line)

        if total_count > 0 and (ascii_count / total_count) >= 0.5:
            print(original_line, end='', file=sys.stdout)
        else:
            print(original_line, end='', file=sys.stderr)

if __name__ == '__main__':
    main()
